language: python
python:
  - 2.7
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=catalogue --cov-report term-missing
after_success:
  - coveralls
