language: python
python:
  - 3.6
before_install:
  - pip install --upgrade pip
  - pip install pytest pytest-cov coveralls
install:
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=catalogue --cov-report term-missing
after_success:
  - coveralls